Merge pull request #12 from iDeboy/master
iDeboy/Attendify pull request #13
Opened 2024-12-08 22:15 UTC by KMUNIVE

Login y Registro, se añadió el contenido de cada uno respectivamente. Para acceder a login será: /login y para acceder a Registro será: /login/registro

2024-12-08 22:16 UTC, KMUNIVE commented
Checar de favor.

2024-12-08 22:20 UTC, iDeboy requested changes
No subiste ningún cambio, primero es "git add .", luego "git commit -m <Mensaje>" y luego el "git push origin <TuRama>"

2024-12-08 23:17 UTC, KMUNIVE commented
se supone que si se hizo

2024-12-09 01:07 UTC, iDeboy commented on App.php
Comentar la linea 7, y en la linea 16 quitar los "--" que estan al inicio

2024-12-09 01:07 UTC, iDeboy commented on Attendify
Quitar esto

2024-12-09 01:08 UTC, iDeboy requested changes
Puse comentarios en los cambios, favor de corregir

2024-12-09 01:17 UTC, KMUNIVE reviewed
Ya esta corregido, checalo

2024-12-09 01:17 UTC, iDeboy approved these changes

2024-12-09 01:18 UTC, merged